apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-go
  template:
    metadata:
      labels:
        app: sidecar-go
    spec:
      containers:
        - name: sidecar-go
          image: sidecar-go:latest
          env:
            - name: RABBIT_URL
              value: amqp://rabbitmq
          ports:
            - containerPort: 3000
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar-go
spec:
  type: LoadBalancer
  selector:
    app: sidecar-go
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: grpc
      port: 50051
      targetPort: 50051
