apiVersion: batch/v1
kind: Job
metadata:
  name: mock-app
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mock-app
          image: mock-app:latest
          env:
            - name: PROVIDER
              value: aws
  backoffLimit: 0
